// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lecsipoddaqsjvoajoof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlY3NpcG9kZGFxc2p2b2Fqb29mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDAzNTIsImV4cCI6MjA3MzY3NjM1Mn0.Ae7iacxIkJrnNVnb91E1QKsrDCtsGh_r17Y5DHu3BgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});